### PR TITLE
Adding library for later HTTP communication with ETCD

### PR DESCRIPTION
**Pull request by 0xdeadbad**

### CODE REVIEW

**Comment by 0xdeadbad** [comment]
Woops, sorry, I made a mistake :facepalm:

**Comment by mwarning** [comment]
No problem :>

But why add a HTTP server?

**Comment by 0xdeadbad** [comment]
> No problem :>
> 
> But why add a HTTP server?

It's actually a HTTP client library. I want to use you SimpleDNS to store A and/or AAAA records on a ETCD cluster via HTTP requests. As long as the ETCD cluster is alive, SimpleDNS could fetch those records from its etcd "database", and create a sorta "Distributed SimpleDNS". My main goal is to try to serve simple name resolution for a container (docker) based cluster and Flannel as a network container overlay. So, I'm just playing around a bit haha

**Comment by mwarning** [comment]
I see. Have fun! :D

**Pull request closed without merging**
