### PR TITLE
Add Fuzzer and add protection against invalid requests received

### PR DESCRIPTION
**Pull request by clementperon**
Hi @mwarning ,

I was looking to write a simple DNS server like this, but found my happiness with this code.

Fuzzer is no running for several minutes and no more issue found after these fixes.

### CODE REVIEW

**Comment by mwarning** [comment]
hi @clementperon, thank you for your contribution! :-)
I will check the code in the next week and take from it what I think would be a good fit for the project.
The code formatting is not something that need to be changed, also CMake is not a good fit for SimeDNS (make is more wide spread compared to cmake  and simpler here). As for a fuzzer, this is learning project, I might add it in a slightly differ way.

**Comment by clementperon** [comment]
@mwarning 

For the code formatting it's easy for me to develop and quickly detect missing characters.
I could try to drop it but this is the default clang-format and it's not far from the actual coding style.

CMake allow me to quickly cross compiled and install the binary when I integrate this project in a distribution builder.
Make is simpler but not really "standard".

**Comment by mwarning** [comment]
I have merged a few minor changes. When I have more time, I will try to also add the memory fixes. But all the commits build on the changed format, so I have to do it manually.

**Comment by mwarning** [comment]
I have added some more fixes and the fuzzer target. Why not also teach safer programming along with the DNS protocol basics. :-)

Thanks. o/

**Pull request closed without merging**
